name: test cucumber
on:
  push:
    branches: [ master ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run cucumber test
        run: |
          touch .env
          API_KEY=${{ secrets.API_KEY }} >> .env
          npm install
          npm run build
          npm run test:cucumber
